spring:
  application:
    name: stress-predict

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stress_prediction_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
      show-sql: true
      open-in-view: true

server:
  port: 8081

security:
  jwt:
    privateKey: 4a0d045593e609435c401089d91421cca7ce6a47425b6541b84f8ef9546955f4
    userGenerator: authJwt-Yoquito