# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://localhost:8000/predict
Content-Type: application/json

{
  "study_hours_per_day": 4.5,
  "extracurricular_hours_per_day": 1.5,
  "sleep_hours_per_day": 7.0,
  "social_hours_per_day": 2.0,
  "physical_activity_hours_per_day": 1.0,
  "gpa": 3.7
}

###

